=== KishanMistryy/Webstack_CIA_1/Emp_Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="Company">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element name="Employee">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Emp_Name" type="xsd:string" />
            <xsd:element name="Emp_Age" type="xsd:integer"/>           
            <xsd:element name="Emp_Salary">
            <xsd:simpleType>
            <xsd:restriction base="xs:integer">
            <xsd:minInclusive value="50000"/>
            <xsd:maxInclusive value="200000"/>
            </xsd:restriction>
            </xsd:simpleType>
            </xsd:element> 
            <xsd:element name="Emp_Email" type="xsd:string"/>
            <xsd:element name="Emp_Phone_Number" type="xsd:string"/>
            <xsd:element name="Emp_Designation" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== KishanMistryy/Webstack_CIA_1/Emp_Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Emp_Style.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Emp_Schema.xsd">
	<Employee id="101">
		<Emp_Name>Nirin Mistry</Emp_Name>
        <Emp_Age> 50 </Emp_Age>
        <Emp_Salary>150000</Emp_Salary>
        <Emp_Email> nirin@gmail.com</Emp_Email>
        <Emp_Phone_Number>7600617193</Emp_Phone_Number>
        <Emp_Designation>CEO</Emp_Designation>        
	</Employee>
    <Employee id="102">
		<Emp_Name>Sohan Mistry</Emp_Name>
        <Emp_Age> 49 </Emp_Age>
        <Emp_Salary>51000</Emp_Salary>
        <Emp_Email> sohan@gmail.com</Emp_Email>
        <Emp_Phone_Number>9600617193</Emp_Phone_Number>
        <Emp_Designation>IT Manager</Emp_Designation>        
	</Employee>
    <Employee id="103">
		<Emp_Name>Kamal Naik</Emp_Name>
        <Emp_Age> 41 </Emp_Age>
        <Emp_Salary>80000</Emp_Salary>
        <Emp_Email> kamal@yahoo.com</Emp_Email>
        <Emp_Phone_Number>7890617193</Emp_Phone_Number>
        <Emp_Designation>Team Manager</Emp_Designation>        
	</Employee>
    <Employee id="104">
		<Emp_Name>Yash Patel</Emp_Name>
        <Emp_Age> 40 </Emp_Age>
        <Emp_Salary>90000</Emp_Salary>
        <Emp_Email> yash@gmail.com</Emp_Email>
        <Emp_Phone_Number>9856741230</Emp_Phone_Number>
        <Emp_Designation>Stock Manager</Emp_Designation>        
	</Employee>
    <Employee id="105">
		<Emp_Name>Hensi Mistry</Emp_Name>
        <Emp_Age> 35 </Emp_Age>
        <Emp_Salary>200000</Emp_Salary>
        <Emp_Email> hensi@gmail.com</Emp_Email>
        <Emp_Phone_Number>9876541230</Emp_Phone_Number>
        <Emp_Designation>CFO</Emp_Designation>        
	</Employee>
</Company>
